### PR TITLE
Final proposed MP_CLOSE description

### PR DESCRIPTION
**Pull request by markusa**

### CODE REVIEW

**Comment by markusa** [comment]
> Due to valid reception of a first DCCP-CloseReq carrying a MP_CLOSE with valid Key Data or due to local decision, all subflows transition to CLOSING state before transmitting **DCCP-Close carrying MP_CLOSE on all subflows.**

> ...

> After this a **DCCP-Reset with Reset Code 1 must be sent on any subflow in response to the at least one received DCCP-Close** with valid MP_CLOSE option.

In rare cases it might be, that no DCCP-Close is sent on a subflow before the DCCP-Reset already arrives. From my understanding this is not problematic, as this has anyway the desired effect of CLOSING the subflow.

**Comment by markusa** [comment]
> In this case, the application socket on the host sending the DCCP-Close reflects the state of the initial subflow used during handshake with MP_KEY option.

Do we need this sentence or is it clear anyway, that application socket and initial subflow socket are the same?

**Review by shjohnson-bt — CHANGES_REQUESTED** [review]
Happy with this - have reworded text slightly though which I have committed on this branch. 

(Not sure if this is the approved way to do this, but thought it was the simplest (for me at least!))

**Comment by markusa** [comment]
Hi Stephen,

> Happy with this - have reworded text slightly though which I have committed on this branch.

Thanks, will merge your suggestions.

> (Not sure if this is the approved way to do this, but thought it was the simplest (for me at least!))

This is exactly the right way


Any comments/thoughts to https://github.com/markusa/ietf-multipath-dccp/pull/73#issuecomment-1136113008 & https://github.com/markusa/ietf-multipath-dccp/pull/73#issuecomment-1136114793?

**Comment by NathalieRM** [comment]
> > In this case, the application socket on the host sending the DCCP-Close reflects the state of the initial subflow used during handshake with MP_KEY option.
> 
> Do we need this sentence or is it clear anyway, that application socket and initial subflow socket are the same?

I think the sentence is necessary, and I also think that the application socket has to be different from any of the subflows sockets. If the application and the initial subflow socket are the same, that would mean that closing the initial subflow would close the whole MP-DCCCP connection, even if there are more subflows available (which shouldn't happen)... or am I missunderstanding something here?

**Review by NathalieRM — APPROVED** [review]

**Review by shjohnson-bt — APPROVED** [review]

**Review by NathalieRM — APPROVED** [review]

**Comment by abrunstrom** [comment]
There are several "must" (and a "has to") in the text. Are any of them supposed to be normative MUST? If not we should rephrase to avoid using "must".

**Comment by markusa** [comment]
> There are several "must" (and a "has to") in the text. Are any of them supposed to be normative MUST? If not we should rephrase to avoid using "must".

Thanks, updated in https://github.com/markusa/ietf-multipath-dccp/pull/73/commits/5ae5eac5dd4e76459a211f8138280c9c477d567a. As there are no further comments PR will be merged.

**Pull request merged**
